/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PokemonIndexRouteImport } from "./routes/pokemon.index"
import { Route as MovesIndexRouteImport } from "./routes/moves.index"
import { Route as PokemonPokemonIdRouteImport } from "./routes/pokemon.$pokemonId"
import { Route as MovesMoveIdRouteImport } from "./routes/moves.$moveId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: "/pokemon/",
  path: "/pokemon/",
  getParentRoute: () => rootRouteImport,
} as any)
const MovesIndexRoute = MovesIndexRouteImport.update({
  id: "/moves/",
  path: "/moves/",
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdRoute = PokemonPokemonIdRouteImport.update({
  id: "/pokemon/$pokemonId",
  path: "/pokemon/$pokemonId",
  getParentRoute: () => rootRouteImport,
} as any)
const MovesMoveIdRoute = MovesMoveIdRouteImport.update({
  id: "/moves/$moveId",
  path: "/moves/$moveId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/moves/$moveId": typeof MovesMoveIdRoute
  "/pokemon/$pokemonId": typeof PokemonPokemonIdRoute
  "/moves": typeof MovesIndexRoute
  "/pokemon": typeof PokemonIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/moves/$moveId": typeof MovesMoveIdRoute
  "/pokemon/$pokemonId": typeof PokemonPokemonIdRoute
  "/moves": typeof MovesIndexRoute
  "/pokemon": typeof PokemonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/moves/$moveId": typeof MovesMoveIdRoute
  "/pokemon/$pokemonId": typeof PokemonPokemonIdRoute
  "/moves/": typeof MovesIndexRoute
  "/pokemon/": typeof PokemonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/moves/$moveId"
    | "/pokemon/$pokemonId"
    | "/moves"
    | "/pokemon"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/moves/$moveId" | "/pokemon/$pokemonId" | "/moves" | "/pokemon"
  id:
    | "__root__"
    | "/"
    | "/moves/$moveId"
    | "/pokemon/$pokemonId"
    | "/moves/"
    | "/pokemon/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovesMoveIdRoute: typeof MovesMoveIdRoute
  PokemonPokemonIdRoute: typeof PokemonPokemonIdRoute
  MovesIndexRoute: typeof MovesIndexRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pokemon/": {
      id: "/pokemon/"
      path: "/pokemon"
      fullPath: "/pokemon"
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/moves/": {
      id: "/moves/"
      path: "/moves"
      fullPath: "/moves"
      preLoaderRoute: typeof MovesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pokemon/$pokemonId": {
      id: "/pokemon/$pokemonId"
      path: "/pokemon/$pokemonId"
      fullPath: "/pokemon/$pokemonId"
      preLoaderRoute: typeof PokemonPokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/moves/$moveId": {
      id: "/moves/$moveId"
      path: "/moves/$moveId"
      fullPath: "/moves/$moveId"
      preLoaderRoute: typeof MovesMoveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovesMoveIdRoute: MovesMoveIdRoute,
  PokemonPokemonIdRoute: PokemonPokemonIdRoute,
  MovesIndexRoute: MovesIndexRoute,
  PokemonIndexRoute: PokemonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
